name: Deploy Serverless Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      SECRET_ID: ${{ secrets.SECRET_ID }}
      ENV_NAME: ${{ secrets.ENV_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli jq zip

      - name: Install Serverless Framework
        run: npm install -g serverless@3.32.1

      - name: Configure AWS credentials for Serverless
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up environment variables
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}
          export ENV_NAME=${{ secrets.ENV_NAME }}

      - name: Retrieve Secrets from AWS Secrets Manager
        run: |
          aws secretsmanager get-secret-value --secret-id ${{ secrets.SECRET_ID }} --region ${{ secrets.AWS_REGION }} | jq -r '.SecretString' | jq -r "to_entries|map(\"\(.key)=\\\"\(.value|tostring)\\\"\")|.[]" > .env

      - name: Install dependencies
        run: npm install

      - name: Create Node.js layer
        run: sh ./scripts/nodejsLayer.sh

      - name: Deploy with Serverless
        run: sls deploy --stage ${ENV_NAME}
