name: Undeploy Serverless Application

on:
  workflow_dispatch:

jobs:
  undeploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ENV_NAME: ${{ secrets.ENV_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Install Serverless Framework
        run: npm install -g serverless@3.32.1

      - name: Configure AWS credentials for Serverless
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Set up environment variables
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}
          export ENV_NAME=${{ secrets.ENV_NAME }}
      - name: Install dependencies
        run: npm install

      - name: Create Node.js layer
        run: sh ./scripts/nodejsLayer.sh

      - name: Undeploy with Serverless
        run: sls remove --stage ${ENV_NAME}
